name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deploy to prod ?"
        required: true
        default: "No"
      environment:
        type: choice
        options:
        - dev
        - prod

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }} "
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}
